[package]
name = "space_invaders"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
futures-timer = "3.0.3"
tokio = { version = "1.39.3", features = ["rt", "macros", "rt-multi-thread"] }
